name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy on every push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install npm dependencies
        run: npm install

      - name: Install yarn dependencies
        run: yarn install

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # Deploying to gh-pages branch
          FOLDER: build
